apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    app: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: rebeccable/mise_en_prod_projet:latest
        ports:
        - containerPort: 8000
        env:
        - name: JETON_API
          valueFrom:
            secretKeyRef:
              name: api-jeton-movie
              key: JETON_API